# Generated by Django 3.2.7 on 2021-09-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherattendance',
            options={},
        ),
    ]
