# Generated by Django 3.2.7 on 2021-09-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_teacherattendance_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherattendance',
            old_name='student',
            new_name='Teacher',
        ),
    ]
