# Generated by Django 3.2.7 on 2021-09-03 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_rename_student_teacherattendance_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='DOB',
        ),
        migrations.AddField(
            model_name='student',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.dept'),
        ),
    ]
